<?php
use \Framework\Tools\Helper\RoutesHelper;
use \Tools\Helper\UserHelper;
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>MyMeals</title>
		<link rel="icon" href="../Assets/images/icons/watermelon.png">
		<link rel="stylesheet" type="text/css" href="../Assets/css/style.css"> 	
		<link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700|Roboto:400,700" rel="stylesheet">
		<script type="text/javascript" src="../Assets/js/jquery/jquery-3.3.1.min.js"></script>
		<script type="text/javascript" src="../Assets/js/jquery/jquery-migrate-1.4.1.min.js"></script>
		<script src="../Assets/js/module/layout.js"></script>
	</head>
	<body>
		<header class="l-header header">
			<nav class="nav">
				<section class="nav__wrapper">
					<span class="nav__brand">
						<a href="<?= RoutesHelper::Path("DisplayHome"); ?>">MyMeals</a>
					</span>

					<span class="nav__menu-user-wrapper">
						<span class="nav__menu">
							<a href="<?= RoutesHelper::Path("DisplayHome"); ?>">Accueil</a>
	<?php if (UserHelper::IsLogin()): ?>
							<a href="<?= RoutesHelper::Path("DisplayPlannifiedMeals"); ?>">Repas</a>
							<a href="<?= RoutesHelper::Path("DisplayShoppingLists"); ?>">Liste</a>
	<?php endif; ?>
							<a href="">Contact</a>
						</span>

						<span class="nav__user">
	<?php if (UserHelper::IsLogin()): ?>
							<a id="logout-link" href="<?= RoutesHelper::Path("UserLogout"); ?>">
								<img class="nav__user__avatar" src="<?= UserHelper::GetAvatarUrl(); ?>"/>
							</a>
	<?php else: ?>
							<a id="login-link" class="button outlined-button light" href="<?= RoutesHelper::Path("UserLogin"); ?>">Se connecter</a>
							<a id="login-link" class="button contained-button light" href="<?= RoutesHelper::Path("UserRegister"); ?>">S'inscrire</a>
	<?php endif; ?>
						</span>
					</span>
				</section>
			</nav>
		</header>
		<main class="l-main main">
			<?php
				if (isset($this->content))
					include($this->content);
			?>
		</main>
		<footer class="l-footer footer">
			<p class="footer__copyright">
				MyMeals © Copyright 2019
			</p>
		</footer>
	</body>
</html>