<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="privacy-display">
        <article>
            <header>
                <h1>Données personnelles</h1>
            </header>
            <section>
                <p>Lors de votre inscription, vous acceptez que soient collecté et conservé votre email. D’autres données facultatives telles que la date de naissance peuvent également être communiquées si vous le souhaitez.</p>
                <p>Les données d’inscription sont uniquement utilisées pour le fonctionnement technique et administratif du site. Les données fournies sont conservées pour la durée d’utilisation de l’utilisateur du site et des services proposés. Ces données sont conservées, en France, dans un environnement technique sécurisé.</p>
                <p>Vous pouvez à tout moment modifier ou supprimer les données personnelles fournies à travers votre espace utilisateur et ainsi exercer votre droit d’accès.</p>
                <p>Si pour une quelconque raison vous ne souhaitez plus conserver votre compte, exprimez votre demande via le formulaire accessible depuis cette page. Une demande légitime est obligatoirement formulée avec le compte dont vous souhaitez obtenir la suppression. Si vous ne pouvez pas vous identifier avec le compte concerné pour confirmer votre identité, votre demande sera malheureusement ignorée pour des raisons évidentes de sécurité.</p>
                <p>Il vous appartient de vous assurer de la confidentialité du ou des mots de passe utilisés. Nous ne disposons d’aucun mot de passe et nous ne saurons être tenu pour responsable en cas de perte ou d’utilisation non conforme de cet élément. Vous êtes invité à signaler toute utilisation non autorisée de votre espace utilisateur.</p>
                <p>Si vous estimez, après nous avoir contactés, que vos droits « Informatique et Libertés » ne sont pas respectés, vous pouvez adresser une réclamation à la <a href="https://www.cnil.fr/">CNIL</a>.</p>
            </section>
        </article>
    </section>
</section>