<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="information">
        <section class="information__wrapper">
            <img src="../../Assets/images/icons/success-circle.svg" class="information__icon--success">
            <h1>Merci !</h1>
            <p>Votre message a bien été envoyé.</p>
            <form method="GET" action="<?= RoutesHelper::Path("DisplayHome"); ?>">
                <button type="submit" class="button contained-button">Ok</button>
            </form>
        </section>
    </section>
</section>