<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="contact-send">
        <section class="contact-send__wrapper">
            <img src="../../Assets/images/icons/check-circle.svg" class="contact-send__icon">
            <h1>Merci !</h1>
            <p>Votre message a bien été envoyé.</p>
            <form method="GET" action="<?= RoutesHelper::Path("DisplayHome"); ?>">
                <button type="submit" class="button contained-button">Ok</button>
            </form>
        </section>
    </section>
</section>