<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="home">
        <section class="home__wrapper">
            <section class="home__images">
                <img src="..//..//Assets//images//icons//strawberry.svg" alt="strawberry"/>
                <img src="..//..//Assets//images//icons//watermelon.svg" alt="watermelon"/>
                <img src="..//..//Assets//images//icons//pear.svg" alt="pear"/>
            </section>

            <section class="home__title">
                <h1 class="home__title__main">Générateur de repas</h1>
                <p class="home__title__secondary">Gagnez du temps et de l'argent.</p>
            </section>
        </section>
    </section>
</section>