<?php
use Framework\Tools\Helper\RoutesHelper;
use Model\Recipe\Recipe;
use Model\Recipe\Instruction;
use Model\Recipe\RecipeIngredient;
use Model\Recipe\Ingredient;
use Model\Meal\Meal;
use Model\Meal\MealMealPart;
use Model\Meal\MealPart;
?>

<section class="l-content content">
    <h1>Bienvenue sur Générateur de repas !</h1>
    <p>Vous pouvez consulter vos repas, les générer, voir votre liste de courses, ...</p>
</section>