<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="information">
        <section class="information__wrapper">
            <img src="../../Assets/images/icons/success-circle.svg" class="information__icon--success">
            <h1>Votre compte a été activé !</h1>
            <p>Votre compte a bien été activé.</p>
            <p>Vous pouvez maintenant vous connecter.</p>
            <form method="GET" action="<?= RoutesHelper::Path("UserLogin"); ?>">
                <button type="submit" class="button contained-button">Ok</button>
            </form>
        </section>
    </section>
</section>