<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="information">
        <section class="information__wrapper">
            <img src="../../Assets/images/icons/error-circle.svg" class="information__icon--error">
            <h1>Lien d'activation invalide !</h1>
            <p>Ce lien d'activation est invalide.</p>
            <p>Votre compte a peut être déjà été activé précédemment.</p>
            <form method="GET" action="<?= RoutesHelper::Path("DisplayHome"); ?>">
                <button type="submit" class="button contained-button">Ok</button>
            </form>
        </section>
    </section>
</section>