<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="login">
        <section class="login__wrapper">
            <form>
                <div class="input input-login">
                    <input type="text" placeholder="Identifiant">
                </div>
                <div class="input input-password">
                    <input type="password" placeholder="Mot de passe">
                </div>

                <div class="wrapper-row-center">
                    <button class="button text-button">S'inscrire</button>
                    <button class="button contained-button button-login">Se connecter</button>
                </div>
            </form>
        </section>
    </section>
</section>