<?php
use Framework\Tools\Helper\RoutesHelper;

$user = $params["User"];
?>

<section class="l-content content">
    <section class="register">
        <h1 class="register__title">Créez votre compte</h1>

        <section class="register__wrapper">
            <form method="POST" action="<?= RoutesHelper::Path("UserRegister"); ?>">
                <div class="register__inputs-wrapper">
                    <div class="register__inputs-wrapper__input input input-login">
                        <input type="text" id="login" name="login" value="<?= $user->GetLogin(); ?>" placeholder="Identifiant" required>
                    </div>
                    <div class="register__inputs-wrapper__input input input-email">
                        <input type="email" id="email" name="email" value="<?= $user->GetEmail(); ?>" placeholder="Adresse e-mail" required>
                    </div>
                    <div class="register__inputs-wrapper__input input input-password">
                        <input type="password" id="password" name="password" placeholder="Mot de passe" required>
                    </div>
                </div>

                <div class="register__buttons-wrapper">
                    <button class="button contained-button">S'inscrire</button>
                </div>
            </form>
        </section>
    </section>
</section>