<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="terms-display">
        <article>
            <header>
                <h1>Mentions légales</h1>
            </header>
            <section>
                <p>Ce site est hébergé par <a href="https://www.ovhcloud.com/fr/">OVHcloud</a></p>
                <address>
                    <p>2 rue Kellermann</p>
                    <p>59100 Roubaix</p>
                    <p>France</p>
                </address>
            </section>
        </article>
    </section>
</section>